services:
  - type: web
    name: ai-resume-analyzer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_sm"
    startCommand: "gunicorn run:app"
    runtime: python3.10